# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api-pmb-test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn run build
      - name: Connect to PostgreSQL
        run: ts-node postgres-client.ts
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
      - name: Unit Testing
        run: yarn run test
        env:
          PORT: 8000
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/api-pmb-test?schema=public
