# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop
  
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: api-pmb-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn run build
      - name: Push tables to database
        run: yarn run test:push
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/api-pmb-test?schema=public
      - name: Seeding database
        run: yarn run test:seed
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/api-pmb-test?schema=public
      - name: Unit Testing
        run: yarn run test
        env:
          PORT: 8000
          DATABASE_URL: postgresql://postgres:password@localhost:5432/api-pmb-test?schema=public
